---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  error = FALSE, warning = FALSE, message = FALSE,
  comment = "#>"
)
```

# DERIVADA TEMPORAL DE XCO₂ PARA IDENTIFICAÇÃO FONTES E SUMIDOUROS DE CARBONO ATMOSFÉRICO NO ESTADO DE SÃO PAULO

Maria Laura Fraque Ferreira, Luis Miguel da Costa, Alan Rodrigo Panosso

**RESUMO** As mudanças climáticas e suas consequências impuseram diversos desafios na atualidade, sendo a principal causa a emissão de gases de efeito estufa (GEE) para a atmosfera, especialmente o dióxido de carbono (CO₂). Embora as emissões globais estejam majoritariamente relacionadas à queima de combustíveis fósseis, no Brasil, as mudanças no uso e cobertura da terra (LULCC, na sigla em inglês) são a principal causa das emissões de CO₂. Essas mudanças estão historicamente associadas à expansão agrícola e ao desmatamento (Souza et al., 2020), com as emissões brasileiras de GEE variando entre 0,4 e 1,7 Gt CO₂ eq em 2022. No Brasil, estudos mostraram correlação negativa entre SIF e a concentração atmosférica de CO2. No entanto, poucas tentativas foram feitas para esclarecer os principais sumidouros de CO2 e a SIF, bem como aspectos relacionados como mudanças no uso e cobertura da terra (LULCC), especialmente considerando os diferentes biomas brasileiros. A hipótese da proposta se baseia na ideia de que fontes e sumidouros de CO2 podem ser identificados por meio da análise de regressão linear simples, e que, com a primeira derivada no tempo (β), é possível classificar pontos específicos como fonte (β > 0) ou sumidouro (β < 0). Assim, os objetivos deste trabalho serão identificar potenciais fontes e sumidouros de CO2 e suas possíveis causas (por exemplo a SIF, desmatamento e focos de incêndio), e estimar rapidamente os fluxos de CO2 no estado de São Paulo a partir de observações via satélite.

